services:
  CRMService:
    image: alldman/crmservice:latest
    container_name: CRMService
    build:
      context: ./src/CRMService
    restart: always
    ports:
      - "8080:8080"
  
  NotificationService:
    image: alldman/notificationservice:latest
    container_name: NotificationService
    build:
      context: ./src/NotificationService
    restart: always
    ports:
      - "8081:8080"
  
  UserService:
    image: alldman/userservice:latest
    container_name: UserService
    build:
      context: ./src/UserService
    restart: always
    ports:
      - "8082:8080"
  
  RabbitMq:
    image: rabbitmq:4.2.0-management-alpine
    container_name: RabbitMq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
        
  UserServiceDb:
    image: postgres:18
    container_name: UserServiceDb
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=user-service-db
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - UserServiceData:/var/lib/postgresql/MAJOR/docker
        
volumes:
  UserServiceData: